### PR TITLE
Prepared for usage with release support.

### PR DESCRIPTION
**Pull request by roelvanhintum**
Please use tags/releases for future releases.

### CODE REVIEW

**Comment by iNalgiev** [comment]
Make sure you add this table ('webtexttool_core') manually or else the edit entry page will give another error. This is because the plugin is loaded differently from other plugins.

**Comment by roelvanhintum** [comment]
As stated in the documentation, craft automatically installs all records on install. So that saves us from a manual step. :)

see: https://craftcms.com/docs/plugins/records

**Comment by iNalgiev** [comment]
That's weird, it didn't install the records on my local installation.

**Comment by roelvanhintum** [comment]
It only triggers after installing. I tried deactivating and activating again, but that didn't work.
Uninstall and install again, should work fine.

**Pull request merged**
